version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - .:/usr/share/nginx/html
    restart: on-failure
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'mydb'
    ports:
      - "3306:3306"
  #  volumes:
  #    - ./docker/mariadb:/etc/mysql/conf.d
  #    - ./docker/db-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
    restart: on-failure
    ports:
      - 81:80
    links:
      - db
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/db-data:/data
    entrypoint: redis-server --appendonly yes
    restart: always
